REQUEST_TIMEOUT = 2

MAX_REQUEST_TRIES = 3
LOG_HTTP_RESPONSES = True

MAX_REQUEST_WAIT_TIME = 15
INITIAL_RETRY_WAIT_TIME = 1
WAIT_EXPONENTIAL_BASE = 3
WAIT_JITTER = 6

MAX_PAGE_RESULTS = 5
MAX_TITLES_BATCH_SIZE = 100
