REQUEST_TIMEOUT = 2

MAX_REQUEST_ATTEMPTS = 3
LOG_HTTP_RESPONSES = True

INITIAL_RETRY_WAIT_TIME = 1
MAX_RETRY_WAIT_TIME = 15
RETRY_WAIT_EXP_BASE = 3
RETRY_WAIT_JITTER = 6

MAX_PAGE_RESULTS = 5
MAX_TITLES_BATCH_SIZE = 100
